#!/bin/bash

ERREUR_ROOT=1
ERREUR_CHOIX=2
#tab : tableau qui contiendra tous les logiciels à installer
##	      tab[0]) gestionnaire de connexion
##	      tab[1]) l'interface graphique
##  de tab[002 à 099]) logiciels ne nécessitant pas d'interface graphique
##  de tab[100 à 199]) logiciels nécessitant une interface graphique (GNOME)
##  de tab[200 à 299]) logiciels nécessitant une interface graphique (KDE)
##  de tab[300 à 399]) logiciels nécessitant une interface graphique (OpenBox)

	[ -n $UID ] || { echo "Il faut être en ROOT ;) " ; exit $ERREUR_ROOT ; }

	pacman -Sy
	pacman -S yaourt
	yaourt -Syu ## Pour être à jour ;)
	
# pré-configuration de pacman.conf
	. include/pacman
# Ma fonction faire_demande
	. include/fonctions

############### Partie utilitaires indispensables #######################

# Les logiciels sans interface graphique
	. include/sans_gui
	
# choix de l'interface graphique
	. include/interface_graphique
	
####### Partie "Logiciels appliqués à une interface graphique" ##########

	if [ "$rep_interface" = "GNOME" ] ; then
		echo "Choisissez les logiciels à installer pour GNOME"
		. include/GNOME		
	elif [ "$rep_interface" = "KDE" ] ; then
		echo "Choisissez les logiciels à installer pour KDE"
		. include/KDE
	fi
		
#### INSTALLATION

	 yaourt -S ${tab[*]}
	 
#### CONFIGURATION

## ajout d'utilisateurs, configuration de sudo, du rc.conf, d'openssh, d'alsa, wifi, conky 
	. include/useradd
	. include/sudoers
	. include/rc	
	. include/openssh
	. include/alsa
	
exit 0
