#!/bin/bash

REPERTOIRE=`pwd`

	ERREUR_ROOT=1
	ERREUR_CHOIX=2
	ERREUR_ARG=3
		
	[ -n $UID ] || { echo "Il faut être en ROOT ;) " ; exit $ERREUR_ROOT ; }
	
	# je prend mes fonctions toutes prêtes :)
	. $REPERTOIRE/include/fonctions
	
	if [ "$#" -lt 1 ] ; then
		. $REPERTOIRE/formulaire
	elif [ "$#" = 1 ] ; then
		case "$1" in 
			"-g" | "--gnome") install_gnome ;;
			"-k" | "--kde") install_kde ;;
			"-s" | "--sans-ig") install_sans_interface ;;
#			"-o" | "--openbox") install_openbox ;;
			"-h" | "--help") echo "Tapez: $0 [--gnome|--kde|--sans-ig]" ;;
			*)  echo "Tapez: $0 [--gnome|--kde|--sans-ig]" && exit $ERREUR_ARG ;;
		esac
	else
		echo "Tapez: $0 [--gnome|--kde|--sans-ig]"
		exit $ERREUR_ARG
	fi
	
	exit 0
