#!/bin/bash

	var_compteur=0
	while [ "$rep_useradd" = "o" ] || [ "$var_compteur" -lt 1 ]
	do
		read -p "Ajout d'un utilisateur o/n : " rep_useradd
		if [ "$rep_useradd" = "o" ] ; then
			
			read -p "nom d'utilisateur (en minuscules) : " rep_username
			useradd "$rep_username"
		fi
		var_compteur=1
	done
